---
#
# Ansible managed
#
repository:
  description: Installing and configuring Telegraf
  homepage: https://buluma.github.io/
  topics: monitoring, telegraf, ansible, molecule, tox, playbook, hacktoberfest
