---
image: "buluma/github-action-molecule:4.0.6"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule -v test
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "debian-systemd"
        tag: "latest"
      - image: "debian"
        tag: "stretch"
      - image: "ubuntu"
        tag: "18.04"
      - image: "ubuntu"
        tag: "20.04"
      - image: "ubuntu"
        tag: "21.04"

testing:
  script:
    - image=${image} tag=${tag} molecule -v test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "debian-systemd"
        tag: "latest"
      - image: "docker-centos8-ansible"
        tag: "latest"
      - image: "docker-centos7-ansible"
        tag: "latest"
      - image: "docker-ubuntu2004-ansible"
        tag: "latest"
      - image: "docker-ubuntu1804-ansible"
        tag: "latest"
      - image: "docker-ubuntu1604-ansible"
        tag: "latest"
      - image: "docker-debian9-ansible"
        tag: "latest"
      - image: "docker-debian8-ansible"
        tag: "latest"

galaxy:
  script:
    - ansible-galaxy role info buluma.telegraf

role_testing:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.telegraf
  retry: 1
  parallel:
    matrix:
      - image: "enterpriselinux"
        tag: "7"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
      - image: "debian-systemd"
        tag: "latest"
