---
roles:
  - name: buluma.bootstrap
  - name: buluma.ca_certificates
  # - name: buluma.pip
collections:
  - name: community.general
  - name: community.aws
  - name: ansible.windows
  - name: community.docker
