---
- name: Restart Telegraf
  when: not telegraf_agent_docker
  block:
    - name: Restart Telegraf
      ansible.builtin.service:
        enabled: true
        name: telegraf
        state: restarted
      become: true
      ignore_errors: "{{ ansible_check_mode }}"
  rescue:
    - name: Debug | Capture telegraf.service journal on restart failure.
      ansible.builtin.command: journalctl -xeu telegraf --no-pager -n 200
      become: true
      changed_when: false
      register: telegraf_journal
    - name: Debug | Print telegraf.service journal.
      ansible.builtin.fail:
        msg: "{{ telegraf_journal.stdout_lines }}"
- name: Restart Telegraf container
  community.docker.docker_container:
    name: "{{ telegraf_agent_docker_name }}"
    restart: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: telegraf_agent_docker
- name: Restart Windows Telegraf
  ansible.windows.win_service:
    name: Telegraf
    start_mode: auto
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
- name: Restart MacOS Telegraf
  ansible.builtin.command: brew services restart telegraf
  changed_when: true
  ignore_errors: "{{ ansible_check_mode }}"
