---
- hosts: all
  gather_facts: true
  become: false

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: buluma.telegraf

  tasks:
    - name: "Installing packages on CentOS"
      ansible.builtin.yum:
        name: which
        state: present
      when:
        - ansible_os_family == 'RedHat'

    - name: "Apt get update"
      shell: apt-get update
      when:
        - ansible_os_family == 'Debian'
      tags:
        - molecule-idempotence-notest

    - name: "Installing packages on Debian"
      ansible.builtin.apt:
        name:
          - wget
          - "{{ 'gnupg-agent' if ansible_distribution_major_version in ['8', '18', '16'] else 'gpg-agent' }}"
        update_cache: True
        state: present
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_major_version not in [9, 10]

    - name: "Installing packages on Debian"
      ansible.builtin.apt:
        name:
          - wget
          - python-apt
          - "{{ 'gnupg-agent' if ansible_distribution_major_version in ['8', '18', '16'] else 'gpg-agent' }}"
        update_cache: True
        state: present
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_major_version in [9, 10]

    - name: "Installing packages on Suse"
      community.general.zypper:
        name:
          - aaa_base
        state: present
      when:
        - ansible_os_family == 'Suse'
