---

- hosts: all
  roles:
    - name: buluma.bootstrap
    - name: buluma.ca_certificates

  tasks:
    - name: "Installing packages on CentOS"
      ansible.builtin.yum:
        name: which
        state: present
      when:
        - ansible_os_family == 'RedHat'

    - name: "Apt get update"
      shell: apt-get update && apt-get install -y python3-apt
      when:
        - ansible_os_family == 'Debian'

    - name: "Installing packages on Debian"
      ansible.builtin.apt:
        name:
          - wget
          - python3-apt
          - "{{ 'gnupg-agent' if ansible_distribution_major_version in ['8', '18', '16'] else 'gpg-agent' }}"
        update_cache: True
        state: present
      when:
        - ansible_os_family == 'Debian'

    - name: "Installing packages on Suse"
      community.general.zypper:
        name:
          - aaa_base
        state: present
      when:
        - ansible_os_family == 'Suse'
