---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check telegraf version
      ansible.builtin.command:
        cmd: telegraf --version
      changed_when: false
